package si.vilfa.junglechronicles.Scene.Objects;

/**
 * @author luka
 * @date 27/11/2021
 * @package si.vilfa.junglechronicles.Scene.Objects
 **/
public enum TerrainBlockType implements BlockType
{
    TERRAIN_TOP_CENTER,
    TERRAIN_TOP_LEFT,
    TERRAIN_TOP_RIGHT,
    TERRAIN_MID_CENTER,
    TERRAIN_MID_LEFT,
    TERRAIN_MID_RIGHT,
    TERRAIN_BOTTOM_CENTER,
    TERRAIN_BOTTOM_LEFT,
    TERRAIN_BOTTOM_RIGHT,
    TERRAIN_PLATFORM_CENTER,
    TERRAIN_PLATFORM_LEFT,
    TERRAIN_PLATFORM_RIGHT,
    TERRAIN_FLOOR_SLOPE_LEFT,
    TERRAIN_FLOOR_SLOPE_RIGHT,
    TERRAIN_CEILING_SLOPE_LEFT,
    TERRAIN_CEILING_SLOPE_RIGHT,
    TERRAIN_CORNER_INNER_BOTTOM_RIGHT,
    TERRAIN_CORNER_INNER_BOTTOM_LEFT,
    TERRAIN_CEILING_LEFT,
    TERRAIN_CEILING_RIGHT,
    MIDGROUND_CENTER,
    MIDGROUND_LEFT,
    MIDGROUND_LEFT_SHADOWED,
    MIDGROUND_RIGHT,
    MIDGROUND_RIGHT_SHADOWED,
    MIDGROUND_SLOPE_LEFT_DOWN,
    MIDGROUND_SLOPE_LEFT_DOWN_SHADOWED,
    MIDGROUND_SLOPE_LEFT_UP,
    MIDGROUND_SLOPE_LEFT_UP_SHADOWED,
    MIDGROUND_SLOPE_RIGHT_DOWN,
    MIDGROUND_SLOPE_RIGHT_DOWN_SHADOWED,
    MIDGROUND_SLOPE_RIGHT_UP,
    MIDGROUND_SLOPE_RIGHT_UP_SHADOWED;

    public static TerrainBlockType getDefault()
    {
        return TERRAIN_TOP_CENTER;
    }
}
